i = 0;

i = i+1;
db(i).mouse_name    = 'ferret942';
db(i).date          = 'F942_Site1_170u_catvid10_v2_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F942_Site1_170u_catvid10_v2_XYT_'
db(i).site          = '1';
db(i).depth         = '170um';
db(i).stimType      = 'NatScenes'
db(i).expts         = [1:10];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';
return
% i = i+1;
% db(i).mouse_name    = 'ferret942';
% db(i).date          = 'F942_Site1_170u_RF_XYT_\'; %'rf_sq';%
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'F942_Site1_170u_RF_XYT_';
% db(i).site          = '1';
% db(i).depth         = '170um';
% db(i).stimType      = 'RF'
% db(i).expts         = [1:2];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';
% return
% i = i+1;
% db(i).mouse_name    = 'ferret942';
% db(i).date          = 'all+natsc_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'all+natsc_'
% db(i).site          = '1';
% db(i).depth         = '170um';
% db(i).stimType      = 'all+natsc_'
% db(i).expts         = [1:10];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';
% 
% return


% 
% i = i+1;
% db(i).mouse_name    = 'ferret942';
% db(i).date          = 'F942_Site1_170u_catvid10_v2_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'F942_Site1_170u_catvid10_v2_XYT_'
% db(i).site          = '1';
% db(i).depth         = '170um';
% db(i).stimType      = 'NatScenes'
% db(i).expts         = [1:10];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';
% 
% i = i+1;
% db(i).mouse_name    = 'ferret942';
% db(i).date          = 'F942_Site1_170u_catvid9_v2_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'F942_Site1_170u_catvid9_v2_XYT_'
% db(i).site          = '1';
% db(i).depth         = '170um';
% db(i).stimType      = 'NatScenes'
% db(i).expts         = [1:10];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';
% 
% i = i+1;
% db(i).mouse_name    = 'ferret942';
% db(i).date          = 'F942_Site1_170u_catvid8_v2_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'F942_Site1_170u_catvid8_v2_XYT_'
% db(i).site          = '1';
% db(i).depth         = '170um';
% db(i).stimType      = 'NatScenes'
% db(i).expts         = [1:10];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';
% 
% i = i+1;
% db(i).mouse_name    = 'ferret942';
% db(i).date          = 'F942_Site1_170u_catvid7_v2_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'F942_Site1_170u_catvid7_v2_XYT_'
% db(i).site          = '1';
% db(i).depth         = '170um';
% db(i).stimType      = 'NatScenes'
% db(i).expts         = [1:10];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';
% 
% 
% i = i+1;
% db(i).mouse_name    = 'ferret942';
% db(i).date          = 'F942_Site1_170u_catvid6_v2_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'F942_Site1_170u_catvid6_v2_XYT_'
% db(i).site          = '1';
% db(i).depth         = '170um';
% db(i).stimType      = 'NatScenes'
% db(i).expts         = [1:10];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';
% 
% i = i+1;
% db(i).mouse_name    = 'ferret942';
% db(i).date          = 'F942_Site1_170u_catvid5_v2_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'F942_Site1_170u_catvid5_v2_XYT_'
% db(i).site          = '1';
% db(i).depth         = '170um';
% db(i).stimType      = 'NatScenes'
% db(i).expts         = [1:10];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';
% 
% i = i+1;
% db(i).mouse_name    = 'ferret942';
% db(i).date          = 'F942_Site1_170u_catvid4_v2_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'F942_Site1_170u_catvid4_v2_XYT_'
% db(i).site          = '1';
% db(i).depth         = '170um';
% db(i).stimType      = 'NatScenes'
% db(i).expts         = [1:10];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';

% i = i+1;
% db(i).mouse_name    = 'ferret942';
% db(i).date          = 'F942_Site1_170u_catvid3_v2_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'F942_Site1_170u_catvid3_v2_XYT_'
% db(i).site          = '1';
% db(i).depth         = '170um';
% db(i).stimType      = 'NatScenes'
% db(i).expts         = [1:6];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret942';
db(i).date          = 'F942_Site1_170u_catvid2_v2_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F942_Site1_170u_catvid2_v2_XYT_'
db(i).site          = '1';
db(i).depth         = '170um';
db(i).stimType      = 'NatScenes'
db(i).expts         = [1:10];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret942';
db(i).date          = 'F942_Site1_170u_catvid1_v2_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F942_Site1_170u_catvid1_v2_XYT_'
db(i).site          = '1';
db(i).depth         = '170um';
db(i).stimType      = 'NatScenes'
db(i).expts         = [1:10];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret942';
db(i).date          = 'F942_Site1_170u_ALL_v2_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F942_Site1_170u_ALL_v2_XYT_'
db(i).site          = '1';
db(i).depth         = '170um';
db(i).stimType      = 'ALL'
db(i).expts         = [1:10];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

return

% i = i+1;
% db(i).mouse_name    = 'ferret942';
% db(i).date          = 'F942_Site1_170u_4q_SM_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'F942_Site1_170u_4q_SM_XYT_'
% db(i).site          = '1';
% db(i).depth         = '170um';
% db(i).stimType      = '4Q'
% db(i).expts         = [1:4];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';

% i = i+1;
% db(i).mouse_name    = 'ferret942';
% db(i).date          = 'F942_Site1_170u_3q_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'F942_Site1_170u_3q_XYT_'
% db(i).site          = '1';
% db(i).depth         = '170um';
% db(i).stimType      = '4Q'
% db(i).expts         = [1:3];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';

return
i = i+1;
db(i).mouse_name    = 'ferret941';
db(i).date          = 'F941_Site2_190u_ORI_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F941_Site2_190u_ORI_XYT_'
db(i).site          = '2';
db(i).depth         = '190um';
db(i).stimType      = 'ORI'
db(i).expts         = [1:5];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret941';
db(i).date          = 'F941_Site3_140u_ORI_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F941_Site3_140u_ORI_XYT_'
db(i).site          = '3';
db(i).depth         = '140um';
db(i).stimType      = 'ORI'
db(i).expts         = [1:4];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret941';
db(i).date          = 'F941_Site3_150u_CatVid1_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F941_Site3_150u_CatVid1_XYT_'
db(i).site          = '3';
db(i).depth         = '150um';
db(i).stimType      = 'NatScene'
db(i).expts         = [1:16];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret941';
db(i).date          = 'F941_Site3_150u_CatVid2_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F941_Site3_150u_CatVid2_XYT_'
db(i).site          = '3';
db(i).depth         = '150um';
db(i).stimType      = 'NatScene'
db(i).expts         = [1:6];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret941';
db(i).date          = 'F941_Site3_150u_NatScene4_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F941_Site3_150u_NatScene4_XYT_'
db(i).site          = '3';
db(i).depth         = '150um';
db(i).stimType      = 'NatScene'
db(i).expts         = [1:20];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret941';
db(i).date          = 'F941_Site3_150u_ORI_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F941_Site3_150u_ORI_XYT_'
db(i).site          = '3';
db(i).depth         = '150um';
db(i).stimType      = 'NatScene'
db(i).expts         = [1:6];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret941';
db(i).date          = 'ORI_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'ORI_XYT_'
db(i).site          = '3';
db(i).depth         = '150um';
db(i).stimType      = 'ORI'
db(i).expts         = [1:5];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';



return

i = i+1;
db(i).mouse_name    = 'ferret914';
db(i).date          = 'F914_Site1_120u_4X_Adapt_0deg_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F914_Site1_120u_4X_Adapt_0deg_XYT_'
db(i).site          = '1';
db(i).depth         = '120um';
db(i).stimType      = 'Adapt'
db(i).expts         = [1:10];
db(i).nchannels     = 2;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret914';
db(i).date          = 'F914_Site1_120u_4X_catvid1_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F914_Site1_120u_4X_catvid1_XYT_'
db(i).site          = '1';
db(i).depth         = '120um';
db(i).stimType      = 'NatScene'
db(i).expts         = [1:7];
db(i).nchannels     = 2;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret914';
db(i).date          = 'F914_Site1_120u_4X_ORI_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F914_Site1_120u_4X_ORI_XYT_'
db(i).site          = '1';
db(i).depth         = '120um';
db(i).stimType      = 'ORI'
db(i).expts         = [1:4];
db(i).nchannels     = 2;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret914';
db(i).date          = 'F914_Site1_120u_4X_SF_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F914_Site1_120u_4X_SF_XYT_'
db(i).site          = '1';
db(i).depth         = '120um';
db(i).stimType      = 'SF'
db(i).expts         = [1:4];
db(i).nchannels     = 2;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret914';
db(i).date          = 'F914_Site1_120u_ORI_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'F914_Site1_120u_ORI_XYT_'
db(i).site          = '1';
db(i).depth         = '120um';
db(i).stimType      = 'ORI'
db(i).expts         = [1:3];
db(i).nchannels     = 2;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

return

i = i+1;
db(i).mouse_name    = 'ferret197-2018';
db(i).date          = 'Site1_150um_ORIset2_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'Site1_150um_ORIset2_XYT_'
db(i).site          = '1';
db(i).depth         = '150um';
db(i).stimType      = 'ORI'
db(i).expts         = [1:5];
db(i).nchannels     = 2;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret197-2018';
db(i).date          = 'Site1_150um_ORI_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'Site1_150um_ORI_XYT_'
db(i).site          = '1';
db(i).depth         = '150um';
db(i).stimType      = 'ORI'
db(i).expts         = [1:4];
db(i).nchannels     = 2;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret197-2018';
db(i).date          = 'Site1_3x_180um_ORI45_AdaptIntervals_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'Site1_3x_180um_ORI45_AdaptIntervals_XYT_'
db(i).site          = '1';
db(i).depth         = '180um';
db(i).stimType      = 'AdaptIntervals'
db(i).expts         = [1:7];
db(i).nchannels     = 2;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret197-2018';
db(i).date          = 'Site1_3x_180um_ORI45_Adapt4_24_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'Site1_3x_180um_ORI45_Adapt4_24_XYT_'
db(i).site          = '1';
db(i).depth         = '180um';
db(i).stimType      = 'Adapt'
db(i).expts         = [1:10];
db(i).nchannels     = 2;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret197-2018';
db(i).date          = 'Site1_3x_180um_ORI_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'Site1_3x_180um_ORI_XYT_'
db(i).site          = '1';
db(i).depth         = '180um';
db(i).stimType      = 'ORI'
db(i).expts         = [1:5];
db(i).nchannels     = 2;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret197-2018';
db(i).date          = 'Site1_3x_150um_ORI225_AdaptIntervals_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'Site1_3x_150um_ORI225_AdaptIntervals_XYT_'
db(i).site          = '1';
db(i).depth         = '150um';
db(i).stimType      = 'AdaptIntervals'
db(i).expts         = [1:10];
db(i).nchannels     = 2;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret197-2018';
db(i).date          = 'Site1_3x_150um_ORI225_Adapt4_24_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'Site1_3x_150um_ORI225_Adapt4_24_XYT_'
db(i).site          = '1';
db(i).depth         = '150um';
db(i).stimType      = 'Adapt'
db(i).expts         = [1:10];
db(i).nchannels     = 2;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';


return
i = i+1;
db(i).mouse_name    = 'ferret227';
db(i).date          = 'Site1_125um_ORI_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'Site1_125um_ORI_XYT_'
db(i).site          = '1';
db(i).depth         = '125um';
db(i).stimType      = 'ORI'
db(i).expts         = [1:3];
db(i).nchannels     = 2;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';
return

i = i+1;
db(i).mouse_name    = 'ferret060';
db(i).date          = 'Day3Site5_120um_4_24_270deg_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'Day3Site5_120um_4_24_270deg_XYT_'
db(i).site          = '5';
db(i).depth         = '120um';
db(i).stimType      = 'Adapt'
db(i).expts         = [1:10];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret060';
db(i).date          = 'Day3Site5_120um_ORI_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'Day3Site5_120um_ORI_XYT_'
db(i).site          = '5';
db(i).depth         = '120um';
db(i).stimType      = 'ORI'
db(i).expts         = [1:4];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret060';
db(i).date          = 'Day3Site5_170um_4_24_67deg_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'Day3Site5_170um_4_24_67deg_XYT_'
db(i).site          = '5';
db(i).depth         = '170um';
db(i).stimType      = 'Adapt'
db(i).expts         = [1:10];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret060';
db(i).date          = 'Day3Site5_170um_4_24_247deg_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'Day3Site5_170um_4_24_247deg_XYT_'
db(i).site          = '5';
db(i).depth         = '170um';
db(i).stimType      = 'Adapt'
db(i).expts         = [1:9];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

i = i+1;
db(i).mouse_name    = 'ferret060';
db(i).date          = 'Day3Site5_170um_ORI_XYT_sq';
db(i).diameter      = 30;
db(i).which2p       = 'sci';
db(i).fb            = 'Day3Site5_170um_ORI_XYT_'
db(i).site          = '5';
db(i).depth         = '170um';
db(i).stimType      = 'ORI'
db(i).expts         = [1:3];
db(i).nchannels     = 1;
db(i).gchannel      = 1; 
db(i).nplanes       = 1; 
db(i).expred        = [];
db(i).nchannels_red = [];
db(i).RootDir       = [];
db(i).comments      = '';

% i = i+1;
% db(i).mouse_name    = 'ferret060';
% db(i).date          = 'Day2Site3ShiftLeft_110um_Adapt4-24_270deg2ndSet_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'Day2Site3ShiftLeft_110um_Adapt4-24_270deg2ndSet_XYT_'
% db(i).site          = '3';
% db(i).depth         = '110um';
% db(i).stimType      = 'Adapt'
% db(i).expts         = [1:8];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';
% 
% i = i+1;
% db(i).mouse_name    = 'ferret060';
% db(i).date          = 'Day2Site4_170um_Adapt4-24_0deg_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'Day2Site4_170um_Adapt4-24_0deg_XYT_'
% db(i).site          = '4';
% db(i).depth         = '170um';
% db(i).stimType      = 'Adapt'
% db(i).expts         = [1:10];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';
% 
% i = i+1;
% db(i).mouse_name    = 'ferret060';
% db(i).date          = 'Day2Site4_170um_Adapt4-24_180deg_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'Day2Site4_170um_Adapt4-24_180deg_XYT_'
% db(i).site          = '4';
% db(i).depth         = '170um';
% db(i).stimType      = 'Adapt'
% db(i).expts         = [1:10];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';
% 
% 
% i = i+1;
% db(i).mouse_name    = 'ferret060';
% db(i).date          = 'Day2Site4_170um_ORI_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'Day2Site4_170um_ORI_XYT_'
% db(i).site          = '4';
% db(i).depth         = '170um';
% db(i).stimType      = 'ORI'
% db(i).expts         = [1:4];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';
% 
% i = i+1;
% db(i).mouse_name    = 'ferret060';
% db(i).date          = 'Day2Site4_200um_Adapt4-24_0deg_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'Day2Site4_200um_Adapt4-24_0deg_XYT_'
% db(i).site          = '4';
% db(i).depth         = '200um';
% db(i).stimType      = 'Adapt'
% db(i).expts         = [1:4];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';
% 
% 
% i = i+1;
% db(i).mouse_name    = 'ferret060';
% db(i).date          = 'Day2Site4_200um_ORI_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'Day2Site4_200um_ORI_XYT_'
% db(i).site          = '4';
% db(i).depth         = '200um';
% db(i).stimType      = 'ORI'
% db(i).expts         = [1:4];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';


% i = i+1;
% db(i).mouse_name    = 'ferret060';
% db(i).date          = 'Site3_130um_3X_ORI__XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'Site3_130um_3X_ORI__XYT_'
% db(i).site          = '3';
% db(i).depth         = '130um';
% db(i).stimType      = 'Adapt'
% db(i).expts         = [1:5];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';
% 
% return
% 
% i = i+1;
% db(i).mouse_name    = 'ferret060';
% db(i).date          = 'Site4_130um_3X_4-24adapt_247deg_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'Site4_130um_3X_4-24adapt_247deg_XYT_'
% db(i).site          = '4';
% db(i).depth         = '130um';
% db(i).stimType      = 'ORI'
% db(i).expts         = [1:9];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1;
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';

% i = i+1;
% db(i).mouse_name    = 'ferret060';
% db(i).date          = 'Site4_130um_3X_ORI_XYT_sq';
% db(i).diameter      = 30;
% db(i).which2p       = 'sci';
% db(i).fb            = 'Site4_130um_3X_ORI_XYT_'
% db(i).site          = '4';
% db(i).depth         = '130um';
% db(i).stimType      = 'ORI'
% db(i).expts         = [1:2];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';


% db(i).mouse_name    = 'ferret059';
% db(i).date          = 'Site1_116u_3X_4_24sadapt_0degsq';
% db(i).diameter      = 40;
% db(i).which2p       = 'sci';
% db(i).fb            = 'Site1_116u_3X_4_24sadapt_0deg_XYT_'
% db(i).site          = '1';
% db(i).depth         = '116um';
% db(i).stimType      = 'Adapt'
% db(i).expts         = [1:4];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';

% db(i).mouse_name    = 'Ferret 934Site1All';
% db(i).date          = '2015-09-08sq';
% db(i).diameter      = 8;
% db(i).which2p       = 'sci';
% db(i).fb            = 'F934_Site1_110u_ALL_XYT_'
% db(i).site          = '1';
% db(i).depth         = '110um';
% db(i).stimType      = 'ALL'
% db(i).expts         = [0:4];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';

% db(i).mouse_name    = 'Ferret 934';
% db(i).date          = '2015-09-08sq';
% db(i).diameter      = 18;
% db(i).which2p       = 'sci';
% db(i).fb            = 'F934_Site1_110u_SF_XYT_(20150908_10_41_30)_ch_1'
% db(i).site          = '1';
% db(i).depth         = '110um';
% db(i).stimType      = 'SF'
% db(i).expts         = [0:3];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [];
% db(i).nchannels_red = [];
% db(i).RootDir       = [];
% db(i).comments      = '';

% i = i+1;
% db(i).mouse_name    = 'M150329_MP009';
% db(i).date          = '2015-04-29';
% db(i).expts         = [4 5 6];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [3];
% db(i).nchannels_red = 2;
% db(i).comments      = 'multi p file: block 4,5,6';
% 
% i = i+1;
% db(i).mouse_name    = 'M150331_MP011';
% db(i).date          = '2015-04-29';
% db(i).expts         = [3 4 6];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [2];
% db(i).nchannels_red = 2;
% db(i).comments      = 'multi p file: block 4,3,6';
% 
% i = i+1;
% db(i).mouse_name    = 'M150422_MP012';
% db(i).date          = '2015-04-28';
% db(i).expts         = [3 4 5];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [2];
% db(i).nchannels_red = 2;
% db(i).comments      = 'multi p file: block 3,4,5';
% 
% i = i+1;
% db(i).mouse_name    = 'M150422_MP012';
% db(i).date          = '2015-05-04';
% db(i).expts         = [2 8];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).comments      = 'single p file: block 2';
% 
% i = i+1;
% db(i).mouse_name    = 'M150422_MP012';
% db(i).date          = '2015-05-20';
% db(i).expts         = [4];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [2];
% db(i).nchannels_red = 2;
% db(i).comments      = 'single p file: block 4';
% 
% i = i+1;
% db(i).mouse_name    = 'M150422_MP015';
% db(i).date          = '2015-05-09';
% db(i).expts         = [2 3];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1;
% db(i).expred        = [1];
% db(i).nchannels_red = 2;
% db(i).comments      = 'single p file, block 3';
% 
% % i = i+1;
% % db(i).mouse_name    = 'M150808_MP016';
% % db(i).date          = '2015-08-24';
% % db(i).expts         = [4];
% % db(i).nchannels     = 1;
% % db(i).gchannel      = 1; 
% % db(i).nplanes       = 1; 
% % db(i).expred        = [3];
% % db(i).nchannels_red = 2;
% % db(i).comments      = 'single p file, block 4, zoom 20';
% 
% i = i+1;
% db(i).mouse_name    = 'M150423_MP014';
% db(i).date          = '2015-06-16';
% db(i).expts         = [8];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1; 
% db(i).expred        = [4];
% db(i).nchannels_red = 2;
% db(i).comments      = 'single p file, block 8 + .3Hz stimulus';
% 
% i = i+1;
% db(i).mouse_name    = 'M150422_MP015';
% db(i).date          = '2015-05-01';
% db(i).expts         = [5 6];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 2;
% db(i).comments      = 'only 1Hz vs 10Hz';
% 
% i = i+1;
% db(i).mouse_name    = 'M150331_MP011';
% db(i).date          = '2015-05-02';
% db(i).expts         = [4 7 8 10 11 12];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1;
% db(i).expred        = [3];
% db(i).nchannels_red = 2;
% db(i).comments      = 'first three running, last three not running';
% 
% i = i+1;
% db(i).mouse_name    = 'M150422_MP015';
% db(i).date          = '2015-04-28';
% db(i).expts         = [3 4 5];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1;
% db(i).expred        = [];
% db(i).nchannels_red = 2;
% db(i).comments      = 'might not be enough signal in this one!';
% 
% i = i+1;
% db(i).mouse_name    = 'M150808_MP016';
% db(i).date          = '2015-08-24';
% db(i).expts         = [4];
% db(i).nchannels     = 1;
% db(i).gchannel      = 1; 
% db(i).nplanes       = 1;
% db(i).expred        = 3;
% db(i).nchannels_red = 2;
% db(i).comments      = 'zoom 20x recording';
